import { ArrowRight, Check, Compass, HeartHandshake, LineChart, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';

const principles = [
  { icon: LineChart, title: 'Make progress visible', text: 'A calm record of the minutes, sessions, and small promises you keep.' },
  { icon: Compass, title: 'Point toward possibility', text: 'Useful opportunities surface when you have the energy to act on them.' },
  { icon: HeartHandshake, title: 'Do it with people', text: 'Shared focus makes ambitious work feel more human and more doable.' },
];

export default function AboutPage() {
  return (
    <div className="space-y-16 pb-8">
      <header className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="font-mono-ui mb-4 text-[10px] uppercase tracking-[.2em] text-primary">The StudyBridge story</p><h1 className="font-display max-w-3xl text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-7xl">Ambition is easier to carry <span className="text-secondary-foreground">together.</span></h1></div><div className="max-w-md"><p className="text-lg leading-relaxed text-muted-foreground">StudyBridge is a place for students who care about what they are building — and want a steady companion while they build it.</p><div className="mt-6 flex items-center gap-3 text-sm font-bold"><span className="grid size-9 place-items-center rounded-full bg-primary text-primary-foreground"><Check size={17} /></span>Built for meaningful momentum</div></div></header>
      <section className="relative overflow-hidden rounded-3xl bg-sidebar p-8 text-sidebar-foreground sm:p-12"><div className="absolute -right-20 -top-28 size-80 rounded-full border-[38px] border-primary/20" /><div className="absolute -bottom-24 right-24 size-52 rounded-full border-[24px] border-secondary/15" /><div className="relative max-w-2xl"><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-primary">Why it exists</p><h2 className="mt-4 font-display text-3xl font-extrabold leading-tight sm:text-4xl">Most study tools measure activity. We wanted to help students trust their own.</h2><p className="mt-5 max-w-xl text-base leading-relaxed text-sidebar-foreground/65">The hard part is rarely knowing what to do. It is starting, returning, asking for help, and noticing that the work is adding up. StudyBridge brings those moments into one warm, purposeful place.</p></div></section>
      <section><div className="mb-8 max-w-xl"><p className="font-mono-ui mb-3 text-[10px] uppercase tracking-[.18em] text-primary">A simple loop</p><h2 className="font-display text-3xl font-extrabold tracking-tight">Attention in. Evidence out.</h2></div><div className="grid gap-4 md:grid-cols-3">{principles.map(({ icon: Icon, title, text }, index) => <div key={title} className="rounded-2xl border border-border/80 bg-card p-6"><span className="font-mono-ui text-xs text-primary">0{index + 1}</span><div className="mt-10 grid size-10 place-items-center rounded-xl bg-secondary text-secondary-foreground"><Icon size={19} /></div><h3 className="mt-5 font-display text-xl font-extrabold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div></section>
      <section className="flex flex-col items-start justify-between gap-6 rounded-2xl border border-primary/30 bg-primary/10 p-7 sm:flex-row sm:items-center sm:p-8"><div><p className="font-display text-2xl font-extrabold">Ready to make the next hour count?</p><p className="mt-1 text-sm text-muted-foreground">Start with one session. Let the proof follow.</p></div><Link href="/sessions" className="focus-ring inline-flex shrink-0 items-center gap-2 rounded-xl bg-sidebar px-4 py-3 text-sm font-bold text-sidebar-foreground hover:bg-sidebar-accent" data-testid="link-about-start-session">Plan a session <ArrowRight size={16} /></Link></section>
      <footer className="flex flex-col justify-between gap-3 border-t border-border/70 pt-6 text-xs text-muted-foreground sm:flex-row"><span className="font-mono-ui uppercase tracking-[.14em]">StudyBridge / 2025</span><span className="inline-flex items-center gap-2"><ShieldCheck size={14} /> A quieter way forward</span></footer>
    </div>
  );
}